### ISSUE TITLE
bash: nr1: command not found

### ISSUE THREAD

**Issue by peefour** [philweber/nr1-process-tree#1]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
I typed this in my terminal:

$ git --version
git version 2.11.0
$ npm -v
3.10.10
$ nr1 nerdpack:clone -r https://github.com/philweber/nr1-process-tree.git                                                                                                      
bash: nr1: command not found
$

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:
s$ uname -a
Linux 123459.cloudwaysapps.com 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
[
## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by philweber** [comment]
Hi, @peefour: Building New Relic nerdpacks requires the [New Relic One command-line interface (CLI)](https://developer.newrelic.com/build-tools/new-relic-one-applications/cli). I have updated the README file to make this more clear. Thank you!
